spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create  #Application 실행시점에 기존 테이블을 다 지우고 새롭게 생성
    properties:
      hibernate:
#        show_sql: true  #logging쪽과 차이점은 show-sql은 systemout으로 출력, logging은 log로
        format_sql: true

logging.level:
  org.hibernate.SQL: debug    #jpa/hibernate 가 생성하는 모든 sql을 눈으로 확인가능
  org.hibernate.type: trace  #SQL 실행 파라미터를 로그로 남긴다
